### ISSUE TITLE
Telegraf: metric parsing error, reason: [missing fields]

### ISSUE THREAD

**Issue by dj-hedgehog** [brightcove/hot-shots#44]
This code:

```
var StatsD = require('hot-shots')
client = new StatsD({
  port: 8094,
  prefix: 'fakt',
  telegraf: true
})

client.increment('stat2')
client.increment('supercount', 1,1 ['mytag', 'prod'])
```

Results for me in this (tried with telegraf set to `true` and `false`):

```
Error in plugin [inputs.socket_listener]: unable to parse incoming packet:  metric parsing error, reason: [missing fields], buffer: [faktstat2:1|c], index: [13]
Error in plugin [inputs.socket_listener]: unable to parse incoming packet:  metric parsing error, reason: [missing fields], buffer: [faktsupercount:1|c], index: [18]
```

What can I do about this?

**Comment by bdeitte** [comment]
I have never used Telegraf unfortunately.  Does it work if you remove prefix?  Perhaps @mmoulton  has an idea here?

**Comment by mmoulton** [comment]
@dj-hedgehog The error message you posted, is that coming from Telegraf or from you node app?

**Comment by dj-hedgehog** [comment]
It is coming from Telegraf itself. I am running the latest version with this docker-compose:

```
version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.2
    ports:
      - 9200:9200
    environment:
      - xpack.monitoring.enabled=false
  telegraf:
    image: telegraf
    volumes:
      - /Users/ali/storyx/infrastructure/elk-stack/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - 8094:9094/udp
    depends_on:
      - elasticsearch
```

This is the input configuration of Telegraf (telegraf.conf)
```
# # Generic socket listener capable of handling multiple socket types.
 [[inputs.socket_listener]]
  service_address = "udp://:8094"
```
